version: "3.9"

services:
  neo4j:
    image: docker.io/neo4j:5.25
    container_name: neo4j
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/internship123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_data:/data
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "internship123", "RETURN 1" ]
      interval: 10s
      timeout: 10s
      retries: 5

  server:
    build:
      context: .
    container_name: python-app
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=internship123
    volumes:
      - .:/app
